### ISSUE TITLE
Conversion of `CuCellArray` to `CPUCellArray`

### ISSUE THREAD

**Issue by albert-de-montserrat** [omlins/CellArrays.jl#33]
Is there any method to quickly transfer a GPU `CellArray` to the CPU. Trying to do `Array(myCellArray)` results into scalar indexing.

**Comment by omlins** [comment]
#45 solves this, enabling: `CPUCellArray(myCellArray)` where `myCellArray` can be any kind. The same works also the other way round. However you need yourself to choose the right B. this will be conserved in these operations

**Comment by albert-de-montserrat** [comment]
Great thanks! Probably you're implementation is neater, I ended up adding this https://github.com/JuliaGeodynamics/JustPIC.jl/blob/75f4ea6f287521c6fb73f3d65ea87e9e6d941c57/src/CellArrays/conversion.jl#L5 (down to L33) to my pkg.
